export const portfolio = {
  name: "Jean-Philippe Marchand",
  initials: "JPM",
  role: "Visual Effects Environment Supervisor & Artist",
  location: "Montreal, Canada",
  resumeUrl: "#contact",
  imdbUrl: "https://www.imdb.com/name/nm6943445/",
  linkedinUrl: "https://www.linkedin.com/in/jpmarchand89/",
  showreelUrl: "https://vimeo.com/1122237782",
  showreelEmbedUrl: "https://player.vimeo.com/video/1122237782?autoplay=1&loop=1&title=0&byline=0&portrait=0",
  showreelBackgroundUrl:
    "https://player.vimeo.com/video/1122237782?background=1&autoplay=1&loop=1&muted=1&controls=0&title=0&byline=0&portrait=0",
  summary:
    "VFX Environment Supervisor and Artist with 15 years of experience building photoreal worlds for feature film and episodic projects, including 8+ years leading teams.",
  about:
    "I specialize in photoreal environments, digital matte painting, camera projection, asset integration, and workflows that help teams move cleanly from creative brief to final pixels. My work spans supervision, hands-on shot work, team leadership, tool development, and practical pipeline problem solving for film, television, and games.",
  metrics: [
    { value: "15+", label: "years in VFX production" },
    { value: "8+", label: "years in leadership roles" },
    { value: "71", label: "confirmed project credits" },
  ],
  skills: [
    "Environment Supervision",
    "Digital Matte Painting",
    "3D Environments",
    "Camera Projection",
    "Compositing",
    "Pipeline Optimization",
    "Tool Development",
    "Team Leadership",
    "Maya",
    "Nuke",
    "Photoshop",
    "Houdini",
    "Unreal Engine",
    "Python",
  ],
  experience: [
    {
      period: "2024 - Present",
      role: "Environment and Matte Painting Artist / Lead",
      company: "Self-employed",
      detail:
        "Creating photoreal environment backgrounds and DMP work for film, games, and media clients, including Folks VFX, Scanline VFX, Pixomondo, BeloFX, Casuarina Studios, and Digital Domain.",
    },
    {
      period: "2025",
      role: "DMP and Environment Artist",
      company: "Scanline VFX",
      detail:
        "Created photoreal environments for major productions, collaborating closely with compositing and lighting teams using Maya, Houdini, Nuke, and Photoshop.",
    },
    {
      period: "2023 - 2025",
      role: "Environment Supervisor",
      company: "Rodeo FX",
      detail:
        "Supervised environment artists through production, established workflows and best practices, developed efficiency tools, reviewed assets, and contributed shot work when needed.",
    },
    {
      period: "2021 - 2023",
      role: "Environment Supervisor",
      company: "Crafty Apes",
      detail:
        "Led environment teams, improved workflows, developed pipeline tools, and partnered with directors and supervisors to deliver each show's creative goals.",
    },
    {
      period: "2015 - 2021",
      role: "DMP, Environment Lead, Matte Painting TD",
      company: "MPC, Scanline VFX, Rodeo FX",
      detail:
        "Led and delivered DMP/environment work across feature film and episodic projects, with earlier roles spanning training, matte painting TD work, and scene assembly.",
    },
  ],
  education: [
    "Associate Degree in 3D Animation & VFX - College Bart, 2012",
    "Associate Degree in Multimedia - College Merici, 2009",
  ],
  contact: {
    email: "jpmarchandcg@gmail.com",
    phone: "1 514 688-9944",
    copy:
      "Send a note for availability, reel details, or project-specific material.",
    defaultMessage:
      "Hi JP, I saw your environment and matte painting portfolio and would like to discuss a project.",
  },
};

export const credits = [
  {
    title: "The Hunger Games: Sunrise on the Reaping",
    year: "2026",
    role: "Digital matte painter",
    type: "Feature Film",
    status: "Post-production",
    poster: "https://upload.wikimedia.org/wikipedia/en/thumb/d/da/The_Hunger_Games_-_Sunrise_on_the_Reaping_poster.jpg/250px-The_Hunger_Games_-_Sunrise_on_the_Reaping_poster.jpg",
    href: "https://www.imdb.com/title/tt32558705/",
  },
  {
    title: "The Woman in Cabin 10",
    year: "2025",
    role: "Visual effects crew: Scanline VFX",
    type: "Feature Film",
    poster: "https://m.media-amazon.com/images/M/MV5BOGZlYmNiNmYtYjlkMi00YmI3LTgxYjEtY2Y0Y2ZjOGQzMGRiXkEyXkFqcGc@._V1_QL75_UX180_CR0,0,180,266_.jpg",
    href: "https://www.imdb.com/title/tt7130300/",
  },
  {
    title: "Black Phone 2",
    year: "2025",
    role: "Digital matte painter",
    type: "Feature Film",
    poster: "https://m.media-amazon.com/images/M/MV5BMTVjMzNmZGYtOWU5NS00NDYzLThhZTktZGNlODIwYWVhMDRmXkEyXkFqcGc@._V1_QL75_UX180_CR0,9,180,266_.jpg",
    href: "https://www.imdb.com/title/tt29644189/",
  },
  {
    title: "Nuremberg",
    year: "2025",
    role: "Digital matte painter",
    type: "Feature Film",
    poster: "https://m.media-amazon.com/images/M/MV5BMWUzODNkYWUtMmMzOC00NzZjLTlkMTctOTkwM2I2ZWI1MTlmXkEyXkFqcGc@._V1_QL75_UX180_CR0,0,180,266_.jpg",
    href: "https://www.imdb.com/title/tt29567915/",
  },
  {
    title: "Manitou's Canoe",
    year: "2025",
    role: "Digital matte painter",
    type: "Feature Film",
    poster: "https://m.media-amazon.com/images/M/MV5BMjA5OGZmNjEtZmFhYS00NWM3LTlhZjItZmIxMzA0NWVhMmY4XkEyXkFqcGc@._V1_QL75_UY266_CR17,0,180,266_.jpg",
    href: "https://www.imdb.com/title/tt30972054/",
  },
  {
    title: "Happy Gilmore 2",
    year: "2025",
    role: "2D artist: Folks VFX; digital matte painter",
    type: "Feature Film",
    poster: "https://m.media-amazon.com/images/M/MV5BYTQyNTRmYjItMDBjYi00YWNhLWEwMmQtNzJhODNiNjEzOWJlXkEyXkFqcGc@._V1_QL75_UX180_CR0,0,180,266_.jpg",
    href: "https://www.imdb.com/title/tt31868189/",
  },
  {
    title: "Murderbot",
    year: "2025",
    role: "Digital Matte Painter",
    type: "TV Series",
    episodes: "1 episode",
    poster: "https://m.media-amazon.com/images/M/MV5BYmFjYTc1ZjUtMmFiMi00NjgzLWJiODgtMDc5ZDcwZmRjYzcwXkEyXkFqcGc@._V1_QL75_UX180_CR0,2,180,266_.jpg",
    href: "https://www.imdb.com/title/tt30444310/",
  },
  {
    title: "The Sandman",
    year: "2025",
    role: "Environment supervisor",
    type: "TV Series",
    episodes: "1 episode",
    poster: "https://m.media-amazon.com/images/M/MV5BNjk0M2ZhZTQtZjQ0NC00ODA2LWFkN2ItMTA0ZTc0MjJjODg0XkEyXkFqcGc@._V1_QL75_UX180_CR0,0,180,266_.jpg",
    href: "https://www.imdb.com/title/tt1751634/",
  },
  {
    title: "The Waterfront",
    year: "2025",
    role: "Digital matte painter",
    type: "TV Series",
    episodes: "1 episode",
    poster: "https://m.media-amazon.com/images/M/MV5BYjllZDZiNzUtZTE5MS00MTNjLWJlMDAtZGY4YjM5YTVkM2UxXkEyXkFqcGc@._V1_QL75_UX180_CR0,0,180,266_.jpg",
    href: "https://www.imdb.com/title/tt31216548/",
  },
  {
    title: "1923",
    year: "2025",
    role: "Digital Matte Painter",
    type: "TV Series",
    episodes: "3 episodes",
    poster: "https://m.media-amazon.com/images/M/MV5BMTU3MGViZTItMmI5NS00MzMwLWFkNjctOGFlNWVmNDM0N2QyXkEyXkFqcGc@._V1_QL75_UX180_CR0,0,180,266_.jpg",
    href: "https://www.imdb.com/title/tt18335752/",
  },
  {
    title: "Mufasa: The Lion King",
    year: "2024",
    role: "Visual effects environment artist: MPC",
    type: "Feature Film",
    poster: "https://m.media-amazon.com/images/M/MV5BYjBkOWUwODYtYWI3YS00N2I0LWEyYTktOTJjM2YzOTc3ZDNlXkEyXkFqcGc@._V1_QL75_UX180_CR0,0,180,266_.jpg",
    href: "https://www.imdb.com/title/tt13186482/",
  },
  {
    title: "Kraven the Hunter",
    year: "2024",
    role: "Matte painting artist: Rodeo FX; visual effects artist",
    type: "Feature Film",
    poster: "https://m.media-amazon.com/images/M/MV5BZDU0YTI5ODAtN2NmMS00YTg3LTgyNDItN2RmOWEzOTkzZjcyXkEyXkFqcGc@._V1_QL75_UX180_CR0,0,180,266_.jpg",
    href: "https://www.imdb.com/title/tt8790086/",
  },
  {
    title: "Salem's Lot",
    year: "2024",
    role: "Environment supervisor",
    type: "Feature Film",
    poster: "https://m.media-amazon.com/images/M/MV5BMTVhN2Y4NDAtYjFmMC00YjI3LTgyMTctYmNmZDhjZmU0MGQ0XkEyXkFqcGc@._V1_QL75_UX180_CR0,0,180,266_.jpg",
    href: "https://www.imdb.com/title/tt10245072/",
  },
  {
    title: "Time Bandits",
    year: "2024",
    role: "Visual effects artist",
    type: "TV Series",
    episodes: "1 episode",
    poster: "https://m.media-amazon.com/images/M/MV5BMWE0ZTdlMWEtYzIwOS00MzRlLWIwYzgtNjlkMWIxYTJiMTc2XkEyXkFqcGc@._V1_QL75_UX180_CR0,2,180,266_.jpg",
    href: "https://www.imdb.com/title/tt1928307/",
  },
  {
    title: "House of the Dragon",
    year: "2024",
    role: "Environment supervisor",
    type: "TV Series",
    episodes: "8 episodes",
    poster: "https://m.media-amazon.com/images/M/MV5BZGM4MTczODQtNGIxOC00Y2U2LTk1YmItNzA2N2VhYmE0Y2YwXkEyXkFqcGc@._V1_QL75_UX180_CR0,0,180,266_.jpg",
    href: "https://www.imdb.com/title/tt11198330/",
  },
  {
    title: "Aquaman and the Lost Kingdom",
    year: "2023",
    role: "Visual effects environment artist: MPC",
    type: "Feature Film",
    poster: "https://m.media-amazon.com/images/M/MV5BYjQ1ZTUzMWMtY2VkNS00ZDRjLWEwODYtYmFkMWJiNTQxMDUzXkEyXkFqcGc@._V1_QL75_UX180_CR0,0,180,266_.jpg",
    href: "https://www.imdb.com/title/tt9663764/",
  },
  {
    title: "The Continental",
    year: "2023",
    role: "Environment supervisor",
    type: "TV Mini Series",
    episodes: "1 episode",
    poster: "https://m.media-amazon.com/images/M/MV5BY2JlMzg0NDktN2FmOC00ZGQwLWI0MDctMDgzZjk0NzMxZWYwXkEyXkFqcGc@._V1_QL75_UX180_CR0,0,180,266_.jpg",
    href: "https://www.imdb.com/title/tt6486762/",
  },
  {
    title: "Beau Is Afraid",
    year: "2023",
    role: "Environment supervisor",
    type: "Feature Film",
    poster: "https://m.media-amazon.com/images/M/MV5BMTdmYmQ5MjctYzU3NS00N2I0LTkwYTYtZWMxNTVhOTRkODA1XkEyXkFqcGc@._V1_QL75_UX180_CR0,0,180,266_.jpg",
    href: "https://www.imdb.com/title/tt13521006/",
  },
  {
    title: "The Last of Us",
    year: "2023",
    role: "Visual effects environment supervisor: Crafty Apes",
    type: "TV Series",
    episodes: "9 episodes",
    poster: "https://m.media-amazon.com/images/M/MV5BYWI3ODJlMzktY2U5NC00ZjdlLWE1MGItNWQxZDk3NWNjN2RhXkEyXkFqcGc@._V1_QL75_UX180_CR0,0,180,266_.jpg",
    href: "https://www.imdb.com/title/tt3581920/",
  },
  {
    title: "The Peripheral",
    year: "2022",
    role: "Environment supervisor: Crafty Apes",
    type: "TV Series",
    episodes: "1 episode",
    poster: "https://m.media-amazon.com/images/M/MV5BODE1NmJiMzAtYmRmZi00ZjkzLWJhZjctNGU0YmFjZWI5NzZmXkEyXkFqcGc@._V1_QL75_UX180_CR0,27,180,266_.jpg",
    href: "https://www.imdb.com/title/tt8291284/",
  },
  {
    title: "Black Adam",
    year: "2022",
    role: "Visual effects crew: Scanline VFX",
    type: "Feature Film",
    poster: "https://m.media-amazon.com/images/M/MV5BYmM3OTM4NDktMmI2NS00OWU0LTg4OTQtNjZhMmFkYjhmOGY1XkEyXkFqcGc@._V1_QL75_UX180_CR0,0,180,266_.jpg",
    href: "https://www.imdb.com/title/tt6443346/",
  },
  {
    title: "Mike",
    year: "2022",
    role: "Environment supervisor: Crafty Apes",
    type: "TV Mini Series",
    episodes: "2 episodes",
    poster: "https://m.media-amazon.com/images/M/MV5BNjM0NWVjYjItMWU5NS00ZmQ3LTk5NGQtMzM2OTY3MjNjMDk3XkEyXkFqcGc@._V1_QL75_UX180_CR0,0,180,266_.jpg",
    href: "https://www.imdb.com/title/tt14181914/",
  },
  {
    title: "The Orville",
    year: "2022",
    role: "Environment supervisor: Crafty Apes",
    type: "TV Series",
    episodes: "1 episode",
    poster: "https://m.media-amazon.com/images/M/MV5BMWU4MDAxMDktNTBjZi00ZTg3LWEzYzItZjkyMjNhMWViMTcwXkEyXkFqcGc@._V1_QL75_UX180_CR0,2,180,266_.jpg",
    href: "https://www.imdb.com/title/tt5691552/",
  },
  {
    title: "The First Lady",
    year: "2022",
    role: "Environment supervisor: Crafty Apes",
    type: "TV Series",
    episodes: "10 episodes",
    poster: "https://m.media-amazon.com/images/M/MV5BNWM5NGFhM2EtNWQwZi00M2RjLWFjMzEtNjFhNzJjNzA2YTViXkEyXkFqcGc@._V1_QL75_UX180_CR0,2,180,266_.jpg",
    href: "https://www.imdb.com/title/tt13223570/",
  },
  {
    title: "God's Favorite Idiot",
    year: "2022",
    role: "Environment supervisor: Crafty Apes",
    type: "TV Series",
    episodes: "8 episodes",
    poster: "https://m.media-amazon.com/images/M/MV5BODJlNmNiNDUtMmQyMi00NzlkLTg2MTktMGI5MWZlYjBlMzFjXkEyXkFqcGc@._V1_QL75_UX180_CR0,2,180,266_.jpg",
    href: "https://www.imdb.com/title/tt13861620/",
  },
  {
    title: "Sonic the Hedgehog 2",
    year: "2022",
    role: "Lead digital artist: MPC",
    type: "Feature Film",
    poster: "https://m.media-amazon.com/images/M/MV5BMDBiYzk0YTMtNWRiYi00YWY0LWE3NjgtYmJiYTAwZmYzOTM0XkEyXkFqcGc@._V1_QL75_UY266_CR0,0,180,266_.jpg",
    href: "https://www.imdb.com/title/tt12412888/",
  },
  {
    title: "Better Nate Than Ever",
    year: "2022",
    role: "Environment supervisor: Crafty Apes",
    type: "Feature Film",
    poster: "https://m.media-amazon.com/images/M/MV5BYzk4MGJkMDItMWVjNC00ZTY0LTg1MGYtZDc4NzM0MWE1NmYxXkEyXkFqcGc@._V1_QL75_UX180_CR0,2,180,266_.jpg",
    href: "https://www.imdb.com/title/tt14696284/",
  },
  {
    title: "The In Between",
    year: "2022",
    role: "Environment supervisor: Crafty Apes",
    type: "Feature Film",
    poster: "https://m.media-amazon.com/images/M/MV5BMjljYzU4ZTctMWM0NC00OTQzLWJmYzItMmNjNzVhOWVmODQ4XkEyXkFqcGc@._V1_QL75_UX180_CR0,0,180,266_.jpg",
    href: "https://www.imdb.com/title/tt8851148/",
  },
  {
    title: "Moonfall",
    year: "2022",
    role: "Digital matte painter: Scanline VFX",
    type: "Feature Film",
    poster: "https://m.media-amazon.com/images/M/MV5BOWY0YzViYzgtMzM5YS00YzI1LTk5MTQtZjdiZjUyZjQ5ZGMwXkEyXkFqcGc@._V1_QL75_UY266_CR4,0,180,266_.jpg",
    href: "https://www.imdb.com/title/tt5834426/",
  },
  {
    title: "Don't Look Up",
    year: "2021",
    role: "Visual effects crew: Scanline VFX",
    type: "Feature Film",
    poster: "https://m.media-amazon.com/images/M/MV5BMjhhNWFjNzctYTJjOS00MDc0LThiNjItZmM0ZDVmMWViY2UzXkEyXkFqcGc@._V1_QL75_UY266_CR17,0,180,266_.jpg",
    href: "https://www.imdb.com/title/tt11286314/",
  },
  {
    title: "The Suicide Squad",
    year: "2021",
    role: "Digital matte painter: Scanline VFX",
    type: "Feature Film",
    poster: "https://m.media-amazon.com/images/M/MV5BMWU3Y2NlZmEtMjJjNS00ZWMxLWE1MzctYWYyMjMzMDdkNTE4XkEyXkFqcGc@._V1_QL75_UX180_CR0,0,180,266_.jpg",
    href: "https://www.imdb.com/title/tt6334354/",
  },
  {
    title: "Cruella",
    year: "2021",
    role: "Lead matte painter: MPC (uncredited)",
    type: "Feature Film",
    poster: "https://m.media-amazon.com/images/M/MV5BMWY5MjljNjctZjhjZS00MWY0LTgwYzUtZTJiYTVmMmJkM2E0XkEyXkFqcGc@._V1_QL75_UX180_CR0,0,180,266_.jpg",
    href: "https://www.imdb.com/title/tt3228774/",
  },
  {
    title: "Zack Snyder's Justice League",
    year: "2021",
    role: "Digital matte painter: Scanline VFX",
    type: "Feature Film",
    poster: "https://m.media-amazon.com/images/M/MV5BNDA0MzM5YTctZTU2My00NGQ5LWE2NTEtNDM0MjZmMDBkOTZkXkEyXkFqcGc@._V1_QL75_UX180_CR0,0,180,266_.jpg",
    href: "https://www.imdb.com/title/tt12361974/",
  },
  {
    title: "The Call of the Wild",
    year: "2020",
    role: "Environment artist: MPC",
    type: "Feature Film",
    poster: "https://m.media-amazon.com/images/M/MV5BYTNmNTBlYzUtNTFiNS00YmY4LWJiMWYtZTlmNmY3ODFlMTUxXkEyXkFqcGc@._V1_QL75_UX180_CR0,0,180,266_.jpg",
    href: "https://www.imdb.com/title/tt7504726/",
  },
  {
    title: "1917",
    year: "2019",
    role: "Lead environment artist: MPC",
    type: "Feature Film",
    poster: "https://m.media-amazon.com/images/M/MV5BYzkxZjg2NDQtMGVjMy00NWZkLTk0ZDEtZWE3NDYwYjAyMTg1XkEyXkFqcGc@._V1_QL75_UX180_CR0,9,180,266_.jpg",
    href: "https://www.imdb.com/title/tt8579674/",
  },
  {
    title: "Maleficent: Mistress of Evil",
    year: "2019",
    role: "Environment artist: MPC",
    type: "Feature Film",
    poster: "https://m.media-amazon.com/images/M/MV5BNTY4YjYwYzMtYTg1NC00ZmJiLTk0OTYtMWMzM2Y4Yzc5MDc2XkEyXkFqcGc@._V1_QL75_UX180_CR0,0,180,266_.jpg",
    href: "https://www.imdb.com/title/tt4777008/",
  },
  {
    title: "X-Men: Dark Phoenix",
    year: "2019",
    role: "Environment artist: MPC",
    type: "Feature Film",
    poster: "https://m.media-amazon.com/images/M/MV5BZjcwMDIyNjctMDVmNS00MzkyLTgxMDMtNTFmNTk0NDkyNzdjXkEyXkFqcGc@._V1_QL75_UX180_CR0,0,180,266_.jpg",
    href: "https://www.imdb.com/title/tt6565702/",
  },
  {
    title: "Godzilla: King of the Monsters",
    year: "2019",
    role: "Environment artist: MPC",
    type: "Feature Film",
    poster: "https://m.media-amazon.com/images/M/MV5BMDVhMjk2OGUtYzYxNS00NzBjLTk5YTItYzI0ZjgzNjY1NmI0XkEyXkFqcGc@._V1_QL75_UX180_CR0,0,180,266_.jpg",
    href: "https://www.imdb.com/title/tt3741700/",
  },
  {
    title: "Aquaman",
    year: "2018",
    role: "VFX trainer",
    type: "Feature Film",
    poster: "https://m.media-amazon.com/images/M/MV5BOTk5ODg0OTU5M15BMl5BanBnXkFtZTgwMDQ3MDY3NjM@._V1_QL75_UX180_CR0,0,180,266_.jpg",
    href: "https://www.imdb.com/title/tt1477834/",
  },
  {
    title: "The Nutcracker and the Four Realms",
    year: "2018",
    role: "Environment artist: MPC",
    type: "Feature Film",
    poster: "https://m.media-amazon.com/images/M/MV5BOTg1NDI1MjEyMl5BMl5BanBnXkFtZTgwOTA5MTgwNjM@._V1_QL75_UX90_CR0,0,90,133_.jpg",
    href: "https://www.imdb.com/title/tt5523010/",
  },
  {
    title: "Jumanji: Welcome to the Jungle",
    year: "2017",
    role: "Digital matte painter: MPC",
    type: "Feature Film",
    poster: "https://m.media-amazon.com/images/M/MV5BZjI5MzdmODctYjA4NS00ZmMxLWJlOWUtOGVhMjA0OGMxMWYzXkEyXkFqcGc@._V1_QL75_UX90_CR0,0,90,133_.jpg",
    href: "https://www.imdb.com/title/tt2283362/",
  },
  {
    title: "Murder on the Orient Express",
    year: "2017",
    role: "Matte painter: MPC",
    type: "Feature Film",
    poster: "https://m.media-amazon.com/images/M/MV5BNTlkYjBlZTctZjg2YS00NDMzLTlkMTMtNWExMGYyOTliMmEzXkEyXkFqcGc@._V1_QL75_UX90_CR0,0,90,133_.jpg",
    href: "https://www.imdb.com/title/tt3402236/",
  },
  {
    title: "The Mummy",
    year: "2017",
    role: "Digital matte painter: MPC",
    type: "Feature Film",
    poster: "https://m.media-amazon.com/images/M/MV5BMTkwMTgwODAxMl5BMl5BanBnXkFtZTgwNTEwNTQ3MDI@._V1_QL75_UX90_CR0,5,90,133_.jpg",
    href: "https://www.imdb.com/title/tt2345759/",
  },
  {
    title: "Pirates of the Caribbean: Dead Men Tell No Tales",
    year: "2017",
    role: "Matte painting TD: Rodeo FX",
    type: "Feature Film",
    poster: "https://m.media-amazon.com/images/M/MV5BMTYyMTcxNzc5M15BMl5BanBnXkFtZTgwOTg2ODE2MTI@._V1_QL75_UX90_CR0,0,90,133_.jpg",
    href: "https://www.imdb.com/title/tt1790809/",
  },
  {
    title: "Alien: Covenant",
    year: "2017",
    role: "Matte painter: MPC (uncredited)",
    type: "Feature Film",
    poster: "https://m.media-amazon.com/images/M/MV5BMjhiYWQ4MTAtOGY1Zi00ZjcyLTk1ZDYtODI3ODRhNjE4MzZhXkEyXkFqcGc@._V1_QL75_UX90_CR0,0,90,133_.jpg",
    href: "https://www.imdb.com/title/tt2316204/",
  },
  {
    title: "The Fate of the Furious",
    year: "2017",
    role: "Matte painting TD: Rodeo FX",
    type: "Feature Film",
    poster: "https://m.media-amazon.com/images/M/MV5BMjMxODI2NDM5Nl5BMl5BanBnXkFtZTgwNjgzOTk1MTI@._V1_QL75_UX90_CR0,5,90,133_.jpg",
    href: "https://www.imdb.com/title/tt4630562/",
  },
  {
    title: "Ghost in the Shell",
    year: "2017",
    role: "Matte painter: MPC",
    type: "Feature Film",
    poster: "https://m.media-amazon.com/images/M/MV5BNzBkNjdjZTctNjdhOS00NmIyLTlkNjQtY2EwNGMwYmZjNTIxXkEyXkFqcGc@._V1_QL75_UX180_CR0,0,180,266_.jpg",
    href: "https://www.imdb.com/title/tt1219827/",
  },
  {
    title: "Black Sails",
    year: "2016-2017",
    role: "Matte painting TD: Rodeo FX; modeler: Rodeo FX",
    type: "TV Series",
    episodes: "7 episodes",
    poster: "https://m.media-amazon.com/images/M/MV5BZGZmOGNjNzUtNTNkMC00ZDU2LThjMDAtZGM2OGRjMjE1OGQ5XkEyXkFqcGc@._V1_QL75_UX90_CR0,1,90,133_.jpg",
    href: "https://www.imdb.com/title/tt2375692/",
  },
  {
    title: "The Shack",
    year: "2017",
    role: "Matte painting TD: Rodeo FX",
    type: "Feature Film",
    poster: "https://m.media-amazon.com/images/M/MV5BMjI3MDMxNzcxNl5BMl5BanBnXkFtZTgwODc4MzkwOTE@._V1_QL75_UX90_CR0,3,90,133_.jpg",
    href: "https://www.imdb.com/title/tt2872518/",
  },
  {
    title: "The Space Between Us",
    year: "2017",
    role: "Matte painting TD: Rodeo FX",
    type: "Feature Film",
    poster: "https://m.media-amazon.com/images/M/MV5BNjYzODU1OTkwN15BMl5BanBnXkFtZTgwMDA3MTMwMDI@._V1_QL75_UX90_CR0,0,90,133_.jpg",
    href: "https://www.imdb.com/title/tt3922818/",
  },
  {
    title: "Kong: Skull Island",
    year: "2017",
    role: "Matte painting TD: Rodeo FX",
    type: "Feature Film",
    poster: "https://m.media-amazon.com/images/M/MV5BMTcwMjcxYTQtYjJlOS00YTE1LWIyZGYtOGRlOTBlMWZmYTliXkEyXkFqcGc@._V1_QL75_UX90_CR0,0,90,133_.jpg",
    href: "https://www.imdb.com/title/tt3731562/",
  },
  {
    title: "Assassin's Creed",
    year: "2016",
    role: "Matte painting TD",
    type: "Feature Film",
    poster: "https://m.media-amazon.com/images/M/MV5BMTU2Mjc1ODY2OV5BMl5BanBnXkFtZTgwNTMzMTYzMDI@._V1_QL75_UX90_CR0,0,90,133_.jpg",
    href: "https://www.imdb.com/title/tt2094766/",
  },
  {
    title: "Resident Evil: The Final Chapter",
    year: "2016",
    role: "Matte painter (uncredited)",
    type: "Feature Film",
    poster: "https://m.media-amazon.com/images/M/MV5BMTc0Mzc2OTQ0Ml5BMl5BanBnXkFtZTgwOTQ5MjE4MDI@._V1_QL75_UX90_CR0,0,90,133_.jpg",
    href: "https://www.imdb.com/title/tt2592614/",
  },
  {
    title: "Fantastic Beasts and Where to Find Them",
    year: "2016",
    role: "Matte painting TD: Rodeo FX",
    type: "Feature Film",
    poster: "https://m.media-amazon.com/images/M/MV5BMjMxOTM1OTI4MV5BMl5BanBnXkFtZTgwODE5OTYxMDI@._V1_QL75_UX90_CR0,0,90,133_.jpg",
    href: "https://www.imdb.com/title/tt3183660/",
  },
  {
    title: "Fear the Walking Dead",
    year: "2016",
    role: "Digital matte painter: Rodeo FX (uncredited)",
    type: "TV Series",
    episodes: "1 episode",
    poster: "https://m.media-amazon.com/images/M/MV5BMDU2YmNiOTktMjE4Ny00NmFhLWIxZTYtOWY0ZWQ4MWM3YjdiXkEyXkFqcGc@._V1_QL75_UX90_CR0,0,90,133_.jpg",
    href: "https://www.imdb.com/title/tt3743822/",
  },
  {
    title: "Miss Peregrine's Home for Peculiar Children",
    year: "2016",
    role: "Matte painter: Rodeo FX",
    type: "Feature Film",
    poster: "https://m.media-amazon.com/images/M/MV5BMTU0Nzc5NzI5NV5BMl5BanBnXkFtZTgwNTk1MDE4MDI@._V1_QL75_UY133_CR8,0,90,133_.jpg",
    href: "https://www.imdb.com/title/tt1935859/",
  },
  {
    title: "The Promise",
    year: "2016",
    role: "Matte painting TD: Rodeo FX",
    type: "Feature Film",
    poster: "https://m.media-amazon.com/images/M/MV5BNzJhYjRiYjYtZGZmZS00MGZmLWI5NWQtZjdlNmEzOGY4YTU2XkEyXkFqcGc@._V1_QL75_UX90_CR0,0,90,133_.jpg",
    href: "https://www.imdb.com/title/tt4776998/",
  },
  {
    title: "Wait Till Helen Comes",
    year: "2016",
    role: "Matte painting TD: Rodeo FX",
    type: "Feature Film",
    poster: "https://m.media-amazon.com/images/M/MV5BMjE2ODYwNjQ0OF5BMl5BanBnXkFtZTgwNjU4NjE3MDI@._V1_QL75_UY133_CR1,0,90,133_.jpg",
    href: "https://www.imdb.com/title/tt1821701/",
  },
  {
    title: "Nine Lives",
    year: "2016",
    role: "Matte painting TD: Rodeo FX",
    type: "Feature Film",
    poster: "https://m.media-amazon.com/images/M/MV5BMzEzMjkwMjc3NV5BMl5BanBnXkFtZTgwMzc0NjY5ODE@._V1_QL75_UX90_CR0,0,90,133_.jpg",
    href: "https://www.imdb.com/title/tt4383594/",
  },
  {
    title: "Star Trek Beyond",
    year: "2016",
    role: "Matte painter; matte painting TD: Rodeo FX",
    type: "Feature Film",
    poster: "https://m.media-amazon.com/images/M/MV5BN2FhNDI1YTYtNWI0OC00ZjYxLWJlYWEtN2ZiZjRmZDY1MWJjXkEyXkFqcGc@._V1_QL75_UX180_CR0,0,180,266_.jpg",
    href: "https://www.imdb.com/title/tt2660888/",
  },
  {
    title: "Central Intelligence",
    year: "2016",
    role: "Matte painter: Rodeo FX",
    type: "Feature Film",
    poster: "https://m.media-amazon.com/images/M/MV5BMjA2NzEzNjIwNl5BMl5BanBnXkFtZTgwNzgwMTEzNzE@._V1_QL75_UX90_CR0,0,90,133_.jpg",
    href: "https://www.imdb.com/title/tt1489889/",
  },
  {
    title: "Warcraft",
    year: "2016",
    role: "Matte painting technical director: Rodeo FX",
    type: "Feature Film",
    poster: "https://m.media-amazon.com/images/M/MV5BMjIwNTM0Mzc5MV5BMl5BanBnXkFtZTgwMDk5NDU1ODE@._V1_QL75_UX90_CR0,5,90,133_.jpg",
    href: "https://www.imdb.com/title/tt0803096/",
  },
  {
    title: "Game of Thrones",
    year: "2015-2016",
    role: "Visual effects: Rodeo FX",
    type: "TV Series",
    episodes: "4 episodes",
    poster: "https://m.media-amazon.com/images/M/MV5BMTNhMDJmNmYtNDQ5OS00ODdlLWE0ZDAtZTgyYTIwNDY3OTU3XkEyXkFqcGc@._V1_QL75_UX90_CR0,1,90,133_.jpg",
    href: "https://www.imdb.com/title/tt0944947/",
  },
  {
    title: "The Divergent Series: Allegiant",
    year: "2016",
    role: "Matte painting TD: Rodeo FX",
    type: "Feature Film",
    poster: "https://m.media-amazon.com/images/M/MV5BMzZlYzZlNDktMDAxMS00OGZiLThkYzAtNWEzNDliYjAyZmM5XkEyXkFqcGc@._V1_QL75_UY133_CR4,0,90,133_.jpg",
    href: "https://www.imdb.com/title/tt3410834/",
  },
  {
    title: "Gods of Egypt",
    year: "2016",
    role: "Matte painter TD: Rodeo FX",
    type: "Feature Film",
    poster: "https://m.media-amazon.com/images/M/MV5BNjExODg3MDUzNl5BMl5BanBnXkFtZTgwNjExMjE3NzE@._V1_QL75_UX90_CR0,3,90,133_.jpg",
    href: "https://www.imdb.com/title/tt2404233/",
  },
  {
    title: "Deadpool",
    year: "2016",
    role: "Matte painter technical director: Rodeo FX",
    type: "Feature Film",
    poster: "https://m.media-amazon.com/images/M/MV5BNzY3ZWU5NGQtOTViNC00ZWVmLTliNjAtNzViNzlkZWQ4YzQ4XkEyXkFqcGc@._V1_QL75_UX180_CR0,2,180,266_.jpg",
    href: "https://www.imdb.com/title/tt1431045/",
  },
  {
    title: "By the Sea",
    year: "2015",
    role: "Matte painting technical director: Rodeo FX (uncredited)",
    type: "Feature Film",
    poster: "https://m.media-amazon.com/images/M/MV5BMTUyNDU2MDMxM15BMl5BanBnXkFtZTgwMzAzMTk1NjE@._V1_QL75_UX90_CR0,5,90,133_.jpg",
    href: "https://www.imdb.com/title/tt3707106/",
  },
  {
    title: "The Last Witch Hunter",
    year: "2015",
    role: "Matte painting technical director: Rodeo FX",
    type: "Feature Film",
    poster: "https://m.media-amazon.com/images/M/MV5BMjM5Njk5MzYzM15BMl5BanBnXkFtZTgwNzM1Mjk4NjE@._V1_QL75_UX90_CR0,2,90,133_.jpg",
    href: "https://www.imdb.com/title/tt1618442/",
  },
  {
    title: "The Little Prince",
    year: "2015",
    role: "Lead CG artist",
    type: "Feature Film",
    poster: "https://m.media-amazon.com/images/M/MV5BNjg0OTM5OTQyNV5BMl5BanBnXkFtZTgwNDg5NDQ0NTE@._V1_QL75_UY133_CR4,0,90,133_.jpg",
    href: "https://www.imdb.com/title/tt1754656/",
  },
  {
    title: "The Pee-Wee 3D: The Winter That Changed My Life",
    year: "2012",
    role: "Visual effects",
    type: "Feature Film",
    poster: "https://m.media-amazon.com/images/M/MV5BNjc3MTA2OTkzMF5BMl5BanBnXkFtZTcwNTkxMTM1OQ@@._V1_QL75_UY133_CR1,0,90,133_.jpg",
    href: "https://www.imdb.com/title/tt2224307/",
  },
  {
    title: "The Guillotines",
    year: "2012",
    role: "Visual effects",
    type: "Feature Film",
    poster: "https://m.media-amazon.com/images/M/MV5BNDQxMDMzODktNzU4ZS00NDU5LWJhYTUtMTE3YmRjYWVlZWU2XkEyXkFqcGc@._V1_QL75_UY133_CR3,0,90,133_.jpg",
    href: "https://www.imdb.com/title/tt1847713/",
  },
];
